server:
  port: 8081
spring:
  profiles:
    active: dev     # 激活8082端口
---
server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8083
spring:
  profiles: test

---
spring:
  mvc:
    date-format:


